version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/load_balancer.conf:/etc/nginx/conf.d/load_balancer.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
